### ISSUE TITLE
Make RunAllTests.m exit only when run by Jenkins

### ISSUE THREAD

**Issue by mvdm** [vandermeerlab/striatal-spike-rhythms#9]
These lines in RunAllTests.m:
```
    if isunix, exit(1); end % hack to only quit on CI machine
end
if isunix, exit; end
```
are annoying when testing on unix machines.

Should be modified to only exit when run on Jenkins. These lines are needed to prevent MATLAB processes piling up on the Jenkins machine.

**Comment by ecarmichael** [comment]
char(java.lang.System.getProperty('user.name'))

this will output the name of the machine
